# Generated by Django 5.1.6 on 2025-06-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Descripción del caso",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_cases",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso clínico",
                "verbose_name_plural": "Casos clínicos",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalImaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Descripción de la imagen",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("preview", "Vista previa"),
                            ("ready", "Lista"),
                            ("processing", "Procesando"),
                            ("analyzed", "Analizada"),
                            ("error", "Error"),
                        ],
                        default="preview",
                        max_length=50,
                        null=True,
                        verbose_name="Estado de la imagen",
                    ),
                ),
                (
                    "full_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="medical_imaging/full_images",
                        verbose_name="Imagen completa",
                    ),
                ),
                (
                    "processed_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="medical_imaging/processed_images",
                        verbose_name="Imagen procesada",
                    ),
                ),
                (
                    "clinical_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_imaging",
                        to="cases.clinicalcase",
                        verbose_name="Caso clínico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen médica",
                "verbose_name_plural": "Imágenes médicas",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LungNodule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "malignancy_type",
                    models.CharField(
                        choices=[
                            ("0", "Altamente Improbable"),
                            ("1", "Moderadamente Improbable"),
                            ("2", "Indeterminado"),
                            ("3", "Moderadamente Sospechoso"),
                            ("4", "Altamente Sospechoso"),
                        ],
                        default="0",
                        max_length=50,
                        verbose_name="Tipo de malignidad",
                    ),
                ),
                (
                    "x_position",
                    models.FloatField(blank=True, null=True, verbose_name="Posición X"),
                ),
                (
                    "y_position",
                    models.FloatField(blank=True, null=True, verbose_name="Posición Y"),
                ),
                (
                    "width",
                    models.FloatField(blank=True, null=True, verbose_name="Ancho"),
                ),
                (
                    "height",
                    models.FloatField(blank=True, null=True, verbose_name="Altura"),
                ),
                (
                    "medical_imaging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lung_nodules",
                        to="cases.medicalimaging",
                        verbose_name="Caso clínico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nódulo pulmonar",
                "verbose_name_plural": "Nódulos pulmonares",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
