# Generated by Django 5.1.6 on 2025-06-18 03:12

import cases.models.medical_imaging
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalimaging",
            name="full_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=cases.models.medical_imaging.full_image_upload_path,
                verbose_name="Imagen completa",
            ),
        ),
        migrations.AlterField(
            model_name="medicalimaging",
            name="processed_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=cases.models.medical_imaging.processed_image_upload_path,
                verbose_name="Imagen procesada",
            ),
        ),
    ]
