# Generated by Django 5.1.6 on 2025-06-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_medicalimaging_full_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lungnodule",
            name="confidence",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Nivel de confianza"
            ),
        ),
    ]
