# Generated by Django 5.1.6 on 2025-06-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "names",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Nombres"
                    ),
                ),
                (
                    "last_names",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de identificación",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("dni", "DNI"),
                            ("ce", "Carnet de extranjería"),
                            ("passport", "Pasaporte"),
                            ("other", "Otro"),
                        ],
                        default="dni",
                        max_length=50,
                        verbose_name="Tipo de identificación",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-updated_at"], "abstract": False,},
        ),
    ]
