# Generated by Django 5.1.6 on 2025-06-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
    ]
