# Generated by Django 5.1.6 on 2025-06-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="clinical_history",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Historia clínica"
            ),
        ),
    ]
