# Generated by Django 5.1.6 on 2025-06-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_patient_clinical_history"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patient", unique_together={("id_number", "id_type")},
        ),
    ]
